// DTN Mythos v12 — test-only classifier (extracted from App.jsx for Node regression)
// Auto-generated by scripts/extract-classifier.sh. Do NOT edit directly —
// edit src/App.jsx and re-run the extraction script.

const STATE_BASELINES={"Andhra Pradesh":45,"Arunachal Pradesh":52,"Assam":29,"Bihar":38,"Chhattisgarh":34,"Goa":40,"Gujarat":35,"Haryana":37,"Himachal Pradesh":53,"Jharkhand":43,"Karnataka":55,"Kerala":64,"Madhya Pradesh":38,"Maharashtra":40,"Manipur":17,"Meghalaya":51,"Mizoram":54,"Nagaland":48,"Odisha":47,"Punjab":50,"Rajasthan":44,"Sikkim":57,"Tamil Nadu":59,"Telangana":49,"Tripura":46,"Uttar Pradesh":26,"Uttarakhand":50,"West Bengal":39,"Delhi":41,"J&K":30};

function classify(h,b){
  const txt=((h||"")+" "+(b||"")).toLowerCase();
  let pillar="justice",dir="negative",delta=-2,violations=[],supports=[],pat="isolated",scope="national",inst=null;
  let evidenceLevel="single_source",storyType="policy",confidence="moderate",courtStatus="none",govResponse=null,citizenExplanation=null;

  // === FIX 3 IN CLASSIFIER: SKIP OBVIOUSLY IRRELEVANT STORIES ===
  // Returns a "skip" flag the caller uses to auto-hold instead of auto-approving.

  // Skip 1 — Future events (nothing has happened yet to analyse)
  // Match when the MAIN action of the headline is future-tense, not when a future date is merely mentioned procedurally.
  // "PM Modi to address nation at 8:30pm" → SKIP (nothing happened)
  // "Court seeks reply; next hearing May 16" → PASS (the seeking is the event)
  const h_lower=(h||"").toLowerCase();
  const futureEvent=
    // Pattern A: headline subject + "to" + verb early in headline (first 10 words)
    /^(?:[\w.']+\s){0,9}\w+\s+to\s+(?:address|speak|announce|meet|deliver|attend|launch|unveil|table|present|move|file|hear|decide|rule|deliberate|inaugurate|release|visit)\b/i.test(h||"")||
    // Pattern B: headline subject + "will" + verb early
    /^(?:[\w.']+\s){0,9}\w+\s+will\s+(?:address|speak|announce|meet|deliver|attend|launch|unveil|table|present|move|file|hear|decide|rule|deliberate|inaugurate|release|visit)\b/i.test(h||"")||
    // Pattern C: specific "set to" / "expected to" / "likely to" phrasings (these are almost always future-only headlines)
    /\b(?:set to|expected to|likely to|scheduled to)\s+(?:address|speak|announce|deliver|attend|launch|unveil|table|present|file|inaugurate)\b/i.test(h_lower)||
    // Pattern D: explicit future-time phrasings with no event happening
    /\b(?:tomorrow|later today|next week|next monday|next tuesday|next wednesday|next thursday|next friday|next saturday|next sunday)\s*[:,-]?\s*(?:pm|am)?\s*(?:modi|cabinet|parliament|sc|supreme court|president|governor)\b/i.test(h_lower)||
    // Pattern E: "at X pm/am today" as the main hook (announcement of future speech)
    /\b(?:to (?:address|speak|deliver))\b[^.]*\bat \d+[:.]?\d*\s*(?:pm|am|hrs)\b/i.test(h_lower);

  // Skip 2 — Foreign stories without Indian constitutional angle
  const foreignOnly=/\bbank of canada\b|\bfederal reserve\b|\beuropean central bank\b|\btrump\b|\bbiden\b|\bobama\b|\bputin\b|\bxi jinping\b|\bkim jong\b|\bmacron\b|\bscholz\b|\bnetanyahu\b|\bzelensky\b|\bbritish parliament\b|\bus congress\b|\bwhite house\b|\beuropean union\b|\bsilicon valley\b|\bwall street\b|\bdowning street\b|\bsan francisco\b|\bnew york times\b|\bwashington post\b|\bhollywood\b|\b(?:louisiana|texas|california|florida|alabama|alaska|arizona|arkansas|colorado|connecticut|georgia|hawaii|idaho|illinois|indiana|iowa|kansas|kentucky|maine|maryland|massachusetts|michigan|minnesota|mississippi|missouri|montana|nebraska|nevada|ohio|oklahoma|oregon|pennsylvania|tennessee|utah|vermont|virginia|wisconsin|wyoming)\s*(?:,|shooting|state|governor|senator)\b|\bpalantir\b|\balex karp\b|\belon musk\b|\bmark zuckerberg\b|\bmeta platforms\b|\bgoogle llc\b|\bamazon\.com\b|\bapple inc\b|\bmicrosoft corp\b|\bopenai\b|\banthropic\b|\bnvidia\b|\bintel corp\b|\bharvard\b|\bstanford\b|\bmit \b|\byale\b|\bprinceton\b|\bcambridge university\b|\boxford university\b|\bmass shooting.*(?:us|united states|america)|\bukraine war\b|\brussia.ukraine\b|\bgaza\b|\bisrael.hamas\b|\bsyria war\b|\byemen war\b|\btaliban\b|\bafghanistan taliban\b|\bimran khan\b|\bshehbaz sharif\b|\bimf loan to\b|\bworld bank report\b|\bun human rights report on (?!india)\b|\bnato\b|\bg7 summit\b|\bg20.*(?!india)\b/i;

  // Skip 3 — Pure noise (sports, entertainment, tech launches)
  const pureNoise=/\b(?:cricket score|football score|ipl match|fifa|olympic|box office|bollywood|hollywood|ott release|trailer|film review|web series|album release|concert|fashion show|iphone|samsung|product launch|startup raises|company earnings|stock price|sensex|nifty|cryptocurrency|bitcoin|horoscope|recipe|weight loss|skincare|beauty tip)\b/i;

  // Skip 4 — Pure campaign rhetoric without policy content (politicians insulting each other)
  const campaignInsult=/\btargets? congress\b|\btargets? bjp\b|\bslams? congress\b|\bslams? bjp\b|\battacks? congress\b|\battacks? bjp\b|\bmocks\b|\btaunts\b|\bjibe at\b|\bdare(?:s|d)? (?:the )?(?:bjp|congress|opposition)\b|\bteach.*lesson\b|\bhave guts\b/i;
  const hasPolicy=/\bbill\b|\bact passed\b|\blaw\b|\bpolicy\b|\border issued\b|\bverdict\b|\bruling\b|\banti.conversion\b|\buapa\b|\bafspa\b|\bnrc\b|\bcaa\b|\bdemolition\b|\bencounter\b|\bcustody\b|\barrest\b|\bdetain\b|\braid(?:s|ed|ing)?\b|\binquiry\b|\bsummon(?:s|ed)?\b|\bfir \b|\bchargesheet\b|\bconviction\b/i;
  const isJustInsult=campaignInsult.test(txt)&&!hasPolicy.test(txt);

  // Skip 5 — Routine operational / procedural news with no constitutional substance
  const routineOp=/court of inquiry (?:ordered|initiated|launched)|hard landing|internal probe|routine audit|administrative transfer|officer suspended pending inquiry|show.cause notice issued/i;
  const hasConstitutionalAngle=/\b(?:custody death|encounter|fake|lynch|demolish|bulldoz|arbitrary arrest|sedition|uapa|afspa|rights violat)/i;
  const isRoutine=routineOp.test(txt)&&!hasConstitutionalAngle.test(txt);

  // Skip 5b — Explainer / listicle / guide content (no actual news event)
  // These are educational filler pieces newspapers publish — "X types of Y", "guide to Z", "all you need to know"
  const listicle=/^\d+ (?:types? of|things|reasons?|ways?|tips?|facts?|benefits?)\b|^(?:a |the )?(?:detailed |complete |comprehensive |ultimate )?guide to\b|\ball you need to know\b|\beverything you should know\b|\bexplained?:?\s*(?:what|how|why|who)\b|\bwhat is\b|\bhow does\b|\btop \d+\b|\blist of\b.*\b(?:types|kinds|varieties)\b|\bdifference between\b|\bvs\.?\s+[A-Z]/i;
  const isListicle=listicle.test(h||"");  // test headline specifically — body may have event keywords

  // Skip 6 — Not obviously India-related
  const indiaAnchor=/\b(?:india|indian|delhi|new delhi|mumbai|bengaluru|bangalore|chennai|kolkata|hyderabad|ahmedabad|pune|lucknow|jaipur|bhopal|patna|chandigarh|guwahati|thiruvananthapuram|ranchi|raipur|dehradun|shimla|gandhinagar|kerala|tamil nadu|karnataka|maharashtra|gujarat|rajasthan|uttar pradesh|\bup\b|bihar|odisha|west bengal|punjab|haryana|telangana|andhra|assam|tripura|meghalaya|mizoram|manipur|nagaland|arunachal|sikkim|goa|jharkhand|chhattisgarh|himachal|uttarakhand|madhya pradesh|j&k|jammu|kashmir|ladakh|modi|rahul|gandhi|sonia|kharge|yogi|mamata|stalin|kejriwal|shah|sitharaman|jaishankar|naidu|nitish|siddaramaiah|fadnavis|adityanath|bjp|congress|\baap\b|tmc|dmk|aiadmk|shiv sena|ncp|rjd|jdu|cpi|cpm|lok sabha|rajya sabha|supreme court|high court|\bsc \b|\bhc \b|chief justice|cji|eci|election commission|rbi|sebi|cag|niti aayog|nhrc|nalsa|iaf|indian army|indian navy|coast guard|prime minister|cabinet|union minister|home minister|finance minister|law minister|external affairs|president of india|droupadi murmu|rashtrapati bhavan|raj bhavan|parliament|constitution|president ram|ambedkar|nehru|patel)\b/i;
  const isNotIndia=!indiaAnchor.test(txt);

  // === v12 ADDITIONS — v11 classifier patterns ===

  // Skip 7 — Weather / natural-phenomena forecasts without accountability angle
  // Pure forecasts ("cyclone to hit coast", "imd predicts heavy rain") are not constitutional.
  // BUT deaths, govt response failure, evacuation mismanagement IS constitutional.
  const weather=/\b(?:weather forecast|monsoon (?:update|to hit|intensifies|arrives|withdraws)|cyclone (?:to hit|warning|alert|approaches|intensifies)|heavy rain (?:expected|predicted|likely)|imd (?:predicts|warns|forecast|issues)|heatwave (?:to intensify|warning|alert)|snow (?:forecast|expected|alert)|fog advisory|temperature (?:to|expected to) (?:rise|drop|soar))\b/i;
  const hasWeatherAccountability=/\b(?:death|killed|dead|drowned|relief (?:delayed|denied|siphoned)|evacuation (?:failed|delayed|mismanaged)|ndrf (?:delayed|refused)|disaster (?:fund|mismanag)|compensation (?:denied|pending)|cag audit|accountab)\b/i;
  const isWeather=weather.test(txt)&&!hasWeatherAccountability.test(txt);

  // Skip 8 — Routine govt announcements / ribbon-cutting (no constitutional substance)
  const announcement=/\b(?:launches? (?:scheme|yojana|portal|app|website|initiative)|inaugurates? (?:project|bridge|highway|building|memorial|statue|flyover)|announces? (?:grant|aid|package|fund disbursement)|flags? off|hands? over keys|unveils? memorial|lays? foundation stone|dedicates? to nation)\b/i;
  const hasAnnouncementIssue=/\b(?:challenged|stayed|pil |protest|caa|nrc|uniform civil code|upa|surveillance|aadhaar mandat|privacy)\b/i;
  const isAnnouncement=announcement.test(txt)&&!hasAnnouncementIssue.test(txt);

  // Skip 9 — Science / discovery / research publications (not constitutional unless tied to policy)
  const scienceDiscovery=/\b(?:new species (?:\w+\s+){0,4}(?:found|discovered|identified|named)|astronomers? (?:find|discover|spot|identify)|researchers? (?:find|identify|discover|map|publish)|scientists? (?:announce|discover|develop|find)|study finds|research paper|published in (?:nature|science|lancet|cell|pnas|bmj)|genome sequenc|fossil (?:found|discovered)|telescope (?:spots|captures))\b/i;
  const isScienceDiscovery=scienceDiscovery.test(h_lower);

  // Skip 10 — "Watch:" / "Viral:" short-form clips without reported-story substance
  const isWatchClip=/^(?:watch|viral|seen this|video|clip)\s*[:|\u2013\u2014-]/i.test(h||"");

  // Skip 11 — Generic crime news without state-level accountability angle
  // Lone-perpetrator crime (robbery, road rage, dowry, etc.) is rarely constitutional on its own.
  // BUT custodial death, encounter, caste atrocity, bulldozing, mob lynching, communal violence ARE.
  const crimeNews=/\b(?:robbed|robbery|stabbed|chain snatch|road rage|burglary|car stolen|bike stolen|mobile theft|pickpocket|atm fraud|online fraud victim|dowry death|dowry harassment|rape accused|murder accused|killed (?:wife|husband|lover))\b/i;
  const hasStateAngleCrime=/\b(?:custody death|custodial (?:death|torture|rape)|encounter (?:killing|death|fake)|police brutality|police fir(?:ing|ed)|lathi charge|caste atrocity|sc\/st atrocity|bulldoz|demolition drive|mob lynch|mob violence|communal violence|honor killing by khap|khap panchayat|minor (?:raped|killed) by (?:police|officer|constable)|tribal (?:killed|evict|displace)|dalit (?:killed|atrocity|assault)|muslim (?:killed|lynch|mob))\b/i;
  const isGenericCrime=crimeNews.test(txt)&&!hasStateAngleCrime.test(txt);

  // If ANY skip reason matches → mark story as skipped and return early
  let skipReason=null;
  if(futureEvent)skipReason="Future event — nothing has happened to analyse yet";
  else if(foreignOnly.test(txt))skipReason="Foreign story without Indian constitutional angle";
  else if(pureNoise.test(txt))skipReason="Sports/entertainment/tech — not constitutional";
  else if(isJustInsult)skipReason="Political rhetoric without policy substance — protected Art.19 speech";
  else if(isRoutine)skipReason="Routine procedural news — accountability mechanism working normally";
  else if(isListicle)skipReason="Explainer/listicle content — no actual news event to analyse";
  else if(isWeather)skipReason="Weather forecast without accountability angle — not constitutional";
  else if(isAnnouncement)skipReason="Routine government announcement — no constitutional question raised";
  else if(isScienceDiscovery)skipReason="Scientific discovery or research — not a constitutional event";
  else if(isWatchClip)skipReason="Short-form video/clip content — no reported-story substance";
  else if(isGenericCrime)skipReason="Generic crime without state-accountability angle — not constitutional";
  else if(isNotIndia)skipReason="Not related to Indian constitutional matters";

  if(skipReason){
    return{
      pillar:"justice",direction:"neutral",delta:0,aiScore:0,
      violations:[],supports:[],institution:null,pattern:"isolated",
      scope:"national",state:null,source:"single_source",
      aiDone:false,aiSkipped:true,skipReason,
      severity:"low",evidenceLevel:"single_source",
      storyType:"policy",confidence:"low",courtStatus:"none",
      govResponse:null,
      citizenExplanation:"This story was filtered out by the relevance engine. Reason: "+skipReason,
      mythos:null,aiAnalysis:null,
    };
  }

  // Institution
  if(/supreme court|high court|sc |hc |judiciary|bench|verdict|judgment|bail|acquit/.test(txt))inst="judiciary";
  else if(/prime minister|pmo|cabinet/.test(txt))inst="pmo";
  else if(/home minister|home ministry|amit shah|central police/.test(txt))inst="home";
  else if(/parliament|lok sabha|rajya sabha|bill |amendment|speaker/.test(txt))inst="law";
  else if(/election commission|eci|ballot|voter|electoral/.test(txt))inst="ec";
  // v12 reorder: media signals take precedence over generic police keywords
  // so a "journalist shot by police" story correctly files as Media, not Police.
  else if(/journalist|reporter|media|press|editor|news channel/.test(txt))inst="media";
  else if(/police|arrested|detained|custody|encounter|cops|constable/.test(txt))inst="police";
  else if(/army|military|afspa|armed force/.test(txt))inst="defence";
  else if(/panchayat|municipality|gram sabha|local body/.test(txt))inst="rural";
  else if(/education|school|university|teacher/.test(txt))inst="education";
  else if(/hospital|health|doctor|medicine|drug/.test(txt))inst="health";
  else if(/forest|environment|tribal|adivasi|displacement/.test(txt))inst="environment";
  else if(/minority|muslim|christian|church|mosque|religious/.test(txt))inst="minority";
  // v12 FIX: "ed " used to match any word ending in "ed " (killED, raideD…) causing
  // random stories to be labelled "Finance". Now require ED-in-context-of-agency-action.
  else if(/\b(?:enforcement directorate|ed raid|ed arrest|ed probe|ed summon|ed attach|ed chargesheet|ed officer|ed action|ed case|pmla case|income tax (?:raid|notice|probe)|cbi (?:raid|arrest|probe|summon|chargesheet|case)|money laundering (?:case|charge|probe)|bank (?:fraud|scam|collapse))\b/.test(txt))inst="finance";
  else if(/\b(?:government|union government|central government|state government|ministry of|\bcm |chief minister|governor of)\b/.test(txt))inst="home";
  // Scope
  if(/village|district|taluk|block/.test(txt))scope="local";
  else if(Object.keys(STATE_BASELINES).some(s=>txt.includes(s.toLowerCase())))scope="state";
  // Evidence level heuristics
  if(/sc |supreme court.*order|high court.*order|gazette|official notification/.test(txt))evidenceLevel="official_doc";
  else if(/court.*stayed|court.*upheld|judgment|verdict/.test(txt))evidenceLevel="court_finding";
  else if(/multiple sources|confirmed|verified|official/.test(txt))evidenceLevel="corroborated";
  else if(/alleged|reportedly|sources say|unconfirmed/.test(txt))evidenceLevel="allegation";
  // Story type
  if(/court|judgment|verdict|bail|acquit/.test(txt))storyType="court";
  else if(/delimitation|bill.*defeat|bill.*pass|parliament|amendment/.test(txt))storyType="law";
  else if(/election|ballot|voter/.test(txt))storyType="election";
  else if(/police|arrested|detained|encounter/.test(txt))storyType="policing";
  else if(/journalist|press|media/.test(txt))storyType="media";
  else if(/corruption|scam|ed |cbi|money laundering/.test(txt))storyType="corruption";
  else if(/dalit|caste|minority|muslim|christian|tribal/.test(txt))storyType="minority";
  else if(/welfare|hospital|school|ration|scheme/.test(txt))storyType="welfare";

  // === Rich constitutional classification with title + who + how (50-80 word explanations) ===

  // DELIMITATION — federal balance, representation — nuanced handling
  if(/delimitation/.test(txt)){
    pillar="electoral";inst=inst||"law";
    if(/defeat|opposition.*block|stall|pause|shelv/.test(txt)){
      // Defeat of delimitation bill — protects south states from losing MPs
      dir="positive";delta=3;
      supports=[
        {a:"Art.82",title:"Delimitation After Census",who:"Opposition MPs in Parliament",how:"The delimitation bill's defeat prevents an immediate redistribution of Lok Sabha seats based on 2021+ population data. Since southern states successfully controlled their population growth while northern states did not, an immediate redraw would have punished south India with fewer MPs. The defeat upholds the 42nd Amendment freeze intent — that family planning success should not reduce political voice."},
        {a:"Art.1",title:"India as Union of States",who:"Parliament's opposition coalition",how:"The defeated bill would have fundamentally altered the federal balance by shifting parliamentary power from south and east to north India. Blocking it preserves the quasi-federal structure envisioned by the Constitution. It signals that demographic changes alone cannot override the cooperative federalism principle that keeps India as a genuine 'Union of States' rather than a majoritarian unitary system."},
        {a:"Art.81",title:"Composition of Lok Sabha",who:"MPs who voted against the bill",how:"Article 81 governs how the 543 Lok Sabha seats are allocated among states. The defeated bill proposed to increase and redistribute these seats based on population alone. The defeat maintains the current balance where population-controlled states retain proportional representation, protecting the constitutional principle that Parliament must represent India's federal diversity, not just its population density."},
        {a:"Art.14",title:"Equality Before Law",who:"Opposition legislators",how:"A straight population-based delimitation would have created unequal political weight — citizens in high-growth states would have had systematically more MPs per capita pull than those in low-growth states. Defeating the bill preserves a more balanced equality of democratic voice across regions. This is a substantive equality reading of Article 14, recognising that mechanical equality by population can mask federal inequality."},
      ];
      citizenExplanation="Parliament defeated a bill that would have redrawn Lok Sabha seats purely on population. South Indian states, which successfully controlled population growth, would have lost seats to northern states — punishing them for good governance. The defeat protects federal balance and equal political voice across regions.";
    }else if(/pass|approv|enact/.test(txt)){
      dir="negative";delta=-4;
      violations=[
        {a:"Art.1",title:"India as Union of States",who:"Parliament majority (ruling government)",how:"The passage of population-based delimitation fundamentally disrupts the federal compact. It rewards states with high population growth and punishes states that successfully implemented family planning — a constitutional perversity. The Union of States principle envisions a balance where no region dominates merely due to population, yet this bill concentrates parliamentary power in a few northern states, weakening quasi-federal governance."},
        {a:"Art.14",title:"Equality Before Law",who:"Government that introduced the bill",how:"Population-only delimitation creates systemic inequality of political voice. Citizens in states like Kerala and Tamil Nadu — which invested in education, health, and family planning — now have fewer MPs per capita issue-representation than citizens in states that did not. This violates substantive equality: the same democratic action (voting, petitioning) produces unequal political outcome based on state of residence."},
        {a:"Art.82",title:"Delimitation After Census",who:"Law Ministry drafters",how:"Article 82 allows delimitation after each census, but constitutional practice has frozen seat allocation since 1976 (42nd Amendment) precisely to protect family-planning states. Lifting the freeze without a compensating federal safeguard — such as upper-house weighting or a minimum-seat floor — breaches the constitutional spirit behind the freeze, even if the letter technically permits redistribution."},
      ];
      citizenExplanation="Parliament passed a bill redrawing Lok Sabha seats based only on population. South Indian states that controlled population growth lose seats to northern states — effectively penalising them for good family-planning outcomes. This weakens federal balance and creates unequal political voice across regions.";
    }else{
      dir="negative";delta=-2;
      violations=[
        {a:"Art.82",title:"Delimitation After Census",who:"Government proposing delimitation",how:"The delimitation process, if based purely on population, threatens to redistribute parliamentary seats away from states that successfully implemented population control — penalising good governance. Article 82 permits periodic delimitation but constitutional convention has paused it precisely to protect federal balance. Any new delimitation must weigh both population and federal representation principles to stay constitutionally sound."},
        {a:"Art.1",title:"India as Union of States",who:"Government planning the redraw",how:"Delimitation directly affects the federal balance encoded in 'Union of States'. A mechanical population formula concentrates parliamentary power in high-growth northern states and reduces the voice of southern and north-eastern states. This development warrants close monitoring because any shift in seat allocation reshapes which regions control national legislation, taxation priorities, and policy direction."},
      ];
      citizenExplanation="A delimitation development is under discussion. How Lok Sabha seats get redistributed based on population directly affects whether southern states — which invested in population control — retain their fair share of MPs, or whether northern states get disproportionate representation.";
    }
  }
  // PRESS FREEDOM
  else if(/journalist|press|media|reporter/.test(txt)){
    pillar="press_freedom";
    if(/kill|murder|dead/.test(txt)){
      delta=-5;evidenceLevel=evidenceLevel==="allegation"?"single_source":evidenceLevel;
      violations=[
        {a:"Art.21",title:"Right to Life and Personal Liberty",who:"State or non-state actor who caused the killing; State for failing Article 355 duty",how:"A journalist's right to life — the most fundamental guarantee of Article 21 — has been extinguished. The Supreme Court has held in Maneka Gandhi (1978) that Article 21 requires the state to proactively protect life, not merely refrain from taking it. When a reporter is killed for their work, the state's failure to provide security and investigate swiftly constitutes a deeper constitutional breach beyond the immediate crime."},
        {a:"Art.19(1)(a)",title:"Freedom of Speech and Expression",who:"Perpetrators and any officials who intimidated the journalist beforehand",how:"Killing a journalist silences not only the victim but every other reporter working on similar stories — a chilling effect the Supreme Court has repeatedly recognised as a violation of Article 19(1)(a). Press freedom is a component of free speech, and violence against journalists is a direct assault on the public's right to receive information essential for democratic participation."},
        {a:"Art.355",title:"Union Duty to Protect States",who:"Union and State governments",how:"Article 355 imposes a duty on both Union and State governments to protect states against internal disturbance. A journalist's killing reveals a failure of this protective duty — whether through inadequate police response, failure to act on prior threats, or indifference. The constitutional question is whether law enforcement treated the journalist's pre-killing complaints with the urgency the Constitution demands."},
      ];
      citizenExplanation="A journalist was killed. This is among the most serious constitutional violations — it destroys the right to life, silences press freedom through fear, and signals state failure to protect those who inform the public.";
    }else if(/arrest|detain|raid/.test(txt)){
      delta=-3;
      violations=[
        {a:"Art.19(1)(a)",title:"Freedom of Speech and Expression",who:"Police and the prosecuting agency",how:"Arresting a journalist for their reporting directly targets press freedom protected under Article 19(1)(a). The Supreme Court in Shreya Singhal (2015) and multiple subsequent rulings has held that speech cannot be criminalised unless it falls within the narrow Article 19(2) exceptions. Using broad laws like UAPA, sedition, or IT Act against journalists without evidence of incitement to violence or public disorder chills legitimate reporting across newsrooms nationwide."},
        {a:"Art.22",title:"Protection Against Arbitrary Arrest",who:"Arresting police and magistrate",how:"Article 22 requires that any arrest be on grounds immediately communicated, with the right to counsel and production before a magistrate within 24 hours. Raids and arrests of journalists often bypass these safeguards — conducted without warrant, without informing the accused of specific charges, and with prolonged detention before magistrate review. This procedural violation compounds the free-speech violation."},
        {a:"Art.21",title:"Right to Life and Personal Liberty",who:"Investigating officer and sanctioning authority",how:"The Supreme Court has held that Article 21 includes the right to live with dignity and without arbitrary state coercion. Targeting journalists with raids, asset freezes, and prolonged pre-trial detention — especially under stringent bail-denying laws — punishes speech through process even before any conviction. This is the 'process as punishment' pattern the Court flagged in Arnab Goswami's bail order (2020)."},
      ];
      citizenExplanation="A journalist was arrested or their news office raided. Beyond the specific case, this chills the wider press — other reporters self-censor fearing similar treatment. The Constitution guarantees press freedom precisely so citizens can access independent information.";
    }else if(/free|release|acquit/.test(txt)){
      dir="positive";delta=2;
      supports=[
        {a:"Art.19(1)(a)",title:"Freedom of Speech and Expression",who:"The court or authority that granted relief",how:"The release or acquittal of a journalist strengthens Article 19(1)(a) by reaffirming that journalism is not a crime. Each such ruling builds precedent protecting future reporters facing similar cases. It signals to investigating agencies that courts will scrutinise prosecution of journalists for free-speech implications, raising the cost of frivolous or politically-motivated cases against the press."},
        {a:"Art.21",title:"Right to Life and Personal Liberty",who:"Court granting bail or quashing charges",how:"Release restores the journalist's personal liberty — the core of Article 21. In the bail jurisprudence developed from Gudikanti Narasimhulu (1978) through Satender Kumar Antil (2022), the Supreme Court has stressed that bail is the rule and jail the exception. A journalist's release operationalises this principle specifically in the press-freedom context, protecting not just the individual but the wider democratic function of journalism."},
      ];
      citizenExplanation="A journalist was freed or a press-freedom case resolved positively. Beyond helping the individual reporter, it sets a precedent that protects every other journalist doing similar work.";
    }else{
      delta=-2;
      violations=[
        {a:"Art.19(1)(a)",title:"Freedom of Speech and Expression",who:"State authority or regulator involved",how:"The incident restricts press freedom — a core component of Article 19(1)(a). The Constitution makes no separate provision for press freedom because the framers intended journalism to be protected within the broader free-speech guarantee. Any regulatory, financial, or operational pressure on news outlets that chills editorial independence engages Article 19(1)(a), even without outright censorship."},
      ];
      citizenExplanation="A journalist or media outlet is facing restrictions. Watch this — it affects how freely the press can report on issues that concern you.";
    }
  }
  // CUSTODY / UAPA / AFSPA — liberty
  else if(/uapa|psa|afspa|custody death|encounter|arbitrary arrest/.test(txt)){
    pillar="liberty";storyType="policing";
    if(/kill|dead|death/.test(txt)){
      delta=-5;evidenceLevel=evidenceLevel==="allegation"?"corroborated":evidenceLevel;
      violations=[
        {a:"Art.21",title:"Right to Life and Personal Liberty",who:"Police personnel involved and their supervising officers",how:"A custodial death or encounter killing extinguishes the victim's Article 21 right to life. In D.K. Basu v. State of West Bengal (1997), the Supreme Court laid down mandatory arrest procedures precisely to prevent such deaths. In PUCL v. State of Maharashtra (2014), the Court mandated independent investigation of every encounter. Violations of these guidelines are treated as direct Article 21 breaches, not merely procedural lapses."},
        {a:"Art.22",title:"Protection Against Arbitrary Arrest and Detention",who:"Arresting officer and magistrate who failed to verify custody conditions",how:"Article 22 guarantees that anyone arrested be informed of grounds, allowed counsel, and produced before a magistrate within 24 hours — safeguards meant to prevent exactly the conditions that lead to custodial deaths. When someone dies in custody before proper magistrate review or without family notification, the state has bypassed every constitutional checkpoint designed to keep detainees alive and documented."},
        {a:"Art.14",title:"Equality Before Law",who:"Policing authority that selected the victim for extraordinary treatment",how:"Encounter killings and custodial deaths disproportionately affect the poor, Dalits, Muslims, and tribal communities — reflecting a two-tier system where state violence operates differently on different social groups. Article 14's equality guarantee demands equal protection of laws, which is breached when some communities face routine extra-judicial violence while others would never be so treated."},
      ];
      citizenExplanation="Someone died in police custody or in an encounter. This is among the severest constitutional violations — the state took a life without the courts, without trial, without the process the Constitution demands before any punishment, let alone death.";
    }else{
      delta=-3;
      violations=[
        {a:"Art.21",title:"Right to Life and Personal Liberty",who:"Investigating agency and sanctioning authority under UAPA/PSA",how:"UAPA, PSA, and AFSPA detentions often bypass the 'procedure established by law' that Article 21 requires — a phrase the Supreme Court in Maneka Gandhi (1978) held must be fair, just, and reasonable, not merely technically legal. Prolonged pre-trial detention, near-impossible bail under UAPA Section 43D(5), and the typical 3-7 year pendency functions as punishment before any finding of guilt."},
        {a:"Art.22",title:"Protection Against Arbitrary Arrest",who:"Police and special tribunal",how:"While Article 22(3) permits preventive detention, the Constitution caps it tightly — with advisory board review within three months and specific protections against vague grounds. UAPA and PSA detentions routinely stretch these limits through chargesheet delays and continued remand extensions. The result is detention that formally complies with statute but violates the constitutional intent that preventive detention remain extraordinary, not routine."},
        {a:"Art.32",title:"Right to Constitutional Remedies",who:"Judiciary slow to hear bail applications",how:"When bail hearings under UAPA routinely take months or years, Article 32's promise of a meaningful remedy becomes hollow. The Supreme Court in Union of India v. KA Najeeb (2021) held that prolonged pre-trial detention itself becomes a ground for constitutional bail, recognising that denial of timely review is itself a rights violation independent of the underlying case."},
      ];
      citizenExplanation="Someone was detained under special laws like UAPA, PSA, or AFSPA. Under these laws, the normal legal process — timely bail, quick trial, specific charges — gets suspended. This weakens personal liberty for everyone because the same laws could be used against any citizen.";
    }
  }
  // ELECTIONS — rig, fraud, court
  else if(/election|voter|ballot|eci|electoral bond/.test(txt)){
    pillar="electoral";
    if(/sc.*struck|court.*quash|upheld/.test(txt)){
      dir="positive";delta=3;evidenceLevel="court_finding";courtStatus="upheld";
      supports=[
        {a:"Art.324",title:"Election Commission Independence",who:"Supreme Court of India",how:"The court's ruling reinforces Article 324, which establishes the Election Commission as an independent constitutional body with superintendence over elections. The Supreme Court in Anoop Baranwal (2023) strengthened this independence by requiring EC appointments through a collegium — a direct attempt to insulate the body from executive capture. Every judgment affirming this independence raises the cost of political interference in election management."},
        {a:"Art.326",title:"Universal Adult Suffrage",who:"Supreme Court bench",how:"Article 326 guarantees every citizen aged 18+ the right to vote on equal terms. Court rulings protecting voter rolls, ballot secrecy, EVM integrity, or anti-defection provisions all operationalise this core democratic right. The judgment prevents executive or administrative measures that would effectively disenfranchise categories of voters through technical or procedural means."},
      ];
      citizenExplanation="A court upheld election fairness. This is positive because every such ruling protects your vote — it sets legal precedent that the same trick cannot be used to undermine elections next time.";
    }else if(/rig|fraud|manipulat/.test(txt)){
      delta=-5;
      violations=[
        {a:"Art.326",title:"Universal Adult Suffrage",who:"Those alleged to have manipulated voter rolls, EVMs, or polling",how:"Allegations of rigging strike at the heart of Article 326 — the promise that every adult citizen gets one equal vote. Whether through bogus voter addition, genuine voter deletion, booth capturing, or EVM tampering, rigging converts democratic elections into contests where the counting process rather than the electorate decides outcomes. Such allegations require swift, independent investigation to preserve faith in the ballot."},
        {a:"Art.324",title:"Election Commission Independence",who:"Election Commission if slow to investigate; political actors who interfered",how:"If rigging occurred under the Election Commission's watch without swift investigation, it indicates either institutional failure or capture. Article 324 gives the EC broad powers — to countermand elections, disqualify candidates, freeze vote counts — precisely so it can respond decisively to fraud. Allegations that remain uninvestigated themselves become a constitutional concern, weakening the EC's claim to independent superintendence."},
        {a:"Art.14",title:"Equality Before Law",who:"Authorities refusing to act equally on similar fraud complaints",how:"Electoral fraud allegations often produce selective investigation — strong action when one party's workers are accused, slow action when the ruling party's workers face similar allegations. This unequal application of electoral law directly violates Article 14's equality guarantee. The constitutional standard is not whether any one investigation happens, but whether all comparable cases receive comparable treatment."},
      ];
      citizenExplanation="There are allegations of election rigging or fraud. If proven, this would mean your vote doesn't actually count — that the real decisions happen in how votes are counted, added, or suppressed, not at the ballot box.";
    }else{
      delta=-2;
      violations=[
        {a:"Art.324",title:"Election Commission Independence",who:"Election Commission or executive influencing electoral process",how:"Electoral process developments warrant careful scrutiny because Article 324 places election integrity in the hands of an independent Commission. Any change in rules, appointments, funding, or procedure can shift the balance between the Commission and the executive. The question for constitutional evaluation is whether this change strengthens or weakens the Commission's ability to conduct free and fair elections."},
        {a:"Art.326",title:"Universal Adult Suffrage",who:"Electoral authorities",how:"Article 326 guarantees universal adult suffrage on an equal basis. Changes to voter rolls, polling procedures, or vote counting directly affect whether every citizen's vote carries equal weight. Even administrative decisions can either expand or shrink the effective franchise, making careful attention to such developments essential for democratic health."},
      ];
      citizenExplanation="An electoral process development may affect how fairly votes are counted or represented. Worth watching for how it unfolds.";
    }
  }
  // CITIZENSHIP — CAA, NRC
  else if(/nrc|caa |citizenship|stateless/.test(txt)){
    pillar="equality";delta=-4;storyType="minority";
    violations=[
      {a:"Art.14",title:"Equality Before Law",who:"Union Government and Parliament",how:"The Citizenship Amendment Act creates a religion-based classification by fast-tracking citizenship for Hindus, Sikhs, Buddhists, Jains, Parsis, and Christians from three neighbouring Muslim-majority countries — while excluding Muslims. The Supreme Court has held in Navtej Johar (2018) and elsewhere that classifications must have a rational nexus to the statute's object. Critics argue that excluding Muslim refugees (Ahmadiyya, Hazara, Rohingya) lacks such nexus and creates unequal access to citizenship based purely on religion."},
      {a:"Art.15",title:"Prohibition of Discrimination on Grounds of Religion",who:"Legislators who passed the law",how:"Article 15 bars the state from discriminating against any citizen solely on grounds of religion. While CAA technically applies to non-citizens seeking naturalisation, combining it with a possible National Register of Citizens creates a two-tier exclusion where Muslims lacking documentation face statelessness while non-Muslims can regain status through CAA. The cumulative effect creates religious discrimination in citizenship access, raising serious Article 15 concerns."},
      {a:"Art.21",title:"Right to Life and Personal Liberty",who:"Executive agencies implementing NRC",how:"Statelessness — loss of citizenship — strips a person of the ability to access services, travel, work, or even vote. The Supreme Court has recognised that Article 21 includes the right to dignified life, which presupposes recognition as a citizen. Detention camps for those excluded from NRC, prolonged legal limbo, and family separation during verification all engage Article 21's dignity guarantee, regardless of formal legal citizenship status."},
    ];
    citizenExplanation="A citizenship policy creates different paths for different religions. Combined with documentation-based exclusion, this may leave some Indian Muslims stateless while offering others a path back — creating unequal treatment based on religion, which the Constitution prohibits.";
  }
  // BULLDOZER — property/dignity
  else if(/bulldoz|demolish|evict/.test(txt)){
    pillar="equality";delta=-3;
    violations=[
      {a:"Art.300A",title:"Right to Property",who:"State authorities conducting the demolition (local municipal body, police, district administration)",how:"Article 300A states no person shall be deprived of property save by authority of law. Bulldozer demolitions typically skip the legal process — no advance notice, no hearing, no opportunity to contest ownership or permit status, no appeal window. The Supreme Court in Re: Manoj Tibrewal Akash (2024) held that arbitrary demolitions without due process violate Article 300A even if the underlying structure is technically unauthorised."},
      {a:"Art.21",title:"Right to Life and Personal Liberty",who:"Executive officials ordering demolition",how:"Article 21 includes the right to shelter — a principle established in Olga Tellis v. Bombay Municipal Corporation (1985), where the Supreme Court held that eviction without alternative accommodation or due process violates the right to livelihood and life. Demolishing homes without proper notice, resettlement provision, or judicial review extinguishes constitutional protections meant to prevent the state from rendering people homeless arbitrarily."},
      {a:"Art.14",title:"Equality Before Law",who:"Authority selecting specific properties for demolition",how:"Bulldozer action often correlates with the identity or political affiliation of the property owner — specifically targeting Muslim households or accused-but-not-convicted individuals. This selective demolition while ignoring identical violations elsewhere violates Article 14's equal protection guarantee. The Supreme Court in Re: Directions in the matter of demolition (2024) mandated advance notice, hearing, and documentation precisely to prevent discriminatory enforcement."},
    ];
    citizenExplanation="Homes were demolished — possibly without proper legal notice or hearing. The Constitution requires that nobody lose their property or home without a fair process, regardless of whether the structure was formally authorised. This protects everyone, not just the targeted individuals.";
  }
  // COURT UPHELD RIGHTS
  else if(/sc.*upheld|court.*protected|acquitted|bail.*granted|sc.*struck down law/.test(txt)){
    pillar="justice";dir="positive";delta=3;evidenceLevel="court_finding";courtStatus="upheld";
    supports=[
      {a:"Art.32",title:"Right to Constitutional Remedies",who:"Supreme Court of India",how:"Article 32 — which Dr. Ambedkar called the 'heart and soul' of the Constitution — guarantees every citizen the right to approach the Supreme Court for enforcement of fundamental rights. When the Court protects rights against executive or legislative overreach, it validates this remedy as a real and effective check, not merely a symbolic one. Each such ruling builds jurisprudence future petitioners can cite when their rights are threatened."},
      {a:"Art.141",title:"Law Declared by Supreme Court is Binding",who:"Supreme Court bench delivering the ruling",how:"Under Article 141, Supreme Court rulings bind every court in India. A judgment protecting constitutional rights thus extends its protection nationwide — any similar case in any lower court must follow the precedent. This multiplier effect means a single ruling can protect thousands of similarly-situated individuals, making Supreme Court constitutional decisions uniquely important for democratic health."},
      {a:"Art.50",title:"Separation of Powers",who:"Judiciary asserting independent review",how:"Article 50 directs the state to separate the judiciary from the executive. When courts strike down executive overreach or unconstitutional legislation, they operationalise this separation. Judicial independence requires not only institutional design but repeated willingness to rule against powerful parties — each such ruling reinforces the constitutional expectation that courts will check other branches rather than defer to them."},
    ];
    citizenExplanation="A court protected constitutional rights. This is a positive outcome with ripple effects — the ruling now becomes precedent that protects anyone else facing similar violations. Court wins are not just about the individual case; they strengthen constitutional protections for everyone.";
  }
  // CASTE / DALIT
  else if(/dalit|caste|sc.st|untouchab|atrocity/.test(txt)){
    pillar="equality";delta=-3;storyType="minority";
    violations=[
      {a:"Art.17",title:"Abolition of Untouchability",who:"Individuals practising the discrimination and state authorities failing to enforce anti-atrocity laws",how:"Article 17 abolishes untouchability 'in any form' — one of the few constitutional provisions that creates a direct individual prohibition, not merely a state duty. When caste discrimination occurs in temples, housing, education, or services, it directly violates Article 17. The Prevention of Atrocities Act operationalises this protection, and failure to register, investigate, or prosecute cases under it effectively nullifies the constitutional ban."},
      {a:"Art.15",title:"Prohibition of Discrimination on Grounds of Caste",who:"Perpetrators and any state officials enabling discrimination",how:"Article 15 prohibits the state from discriminating on grounds including caste. While Article 15 restrains state action, Article 15(2) extends this to private actors regarding access to shops, public restaurants, hotels, and wells maintained for public use. Caste-based exclusion from these spaces directly violates the Constitution. The state's duty under Article 15(4) to make special provisions for backward classes means indifference to atrocities is itself a constitutional breach."},
      {a:"Art.46",title:"Promotion of Educational and Economic Interests of Weaker Sections",who:"State failing in its directive principle duty",how:"Article 46 directs the state to promote the educational and economic interests of Scheduled Castes and Scheduled Tribes and protect them from social injustice and exploitation. While directive principles are not directly enforceable, they guide legislation and administration. Routine failure to prevent caste atrocities, provide timely relief, or prosecute cases indicates the state has abdicated this constitutional direction."},
      {a:"Art.21",title:"Right to Life and Personal Liberty",who:"Perpetrators; state if it failed to protect",how:"Caste atrocities that result in death, injury, or sustained humiliation violate Article 21's guarantee of life and dignity. The Supreme Court in Francis Coralie Mullin (1981) held that the right to life includes the right to live with human dignity. Forced consumption of waste, parading naked, public humiliation, or killing over inter-caste marriage all violate this dignity component directly."},
    ];
    citizenExplanation="A caste-based discrimination or atrocity is reported. The Constitution bans untouchability and caste discrimination explicitly — Article 17 is one of the strongest provisions because it creates a direct ban. The state has a constitutional duty to prevent and punish such incidents.";
  }
  // TRIBAL / ADIVASI
  else if(/tribal|adivasi|forest right|displacement/.test(txt)){
    pillar="environment";delta=-3;scope="state";inst=inst||"environment";
    violations=[
      {a:"5th Sch",title:"Fifth Schedule — Tribal Areas and Scheduled Areas",who:"State government and mining/infrastructure authorities",how:"The Fifth Schedule gives Governors special powers to regulate laws in Scheduled Areas to protect tribal land and culture. Samatha v. State of Andhra Pradesh (1997) held that tribal land in Scheduled Areas cannot be leased to non-tribals or private companies — it must remain with Scheduled Tribe owners. Displacement for mining or development without tribal consent, rehabilitation, or PESA compliance directly violates these constitutional protections meant to prevent tribal dispossession."},
      {a:"Art.21",title:"Right to Life and Personal Liberty",who:"Executive ordering displacement",how:"The Supreme Court in Narmada Bachao Andolan (2000) held that displacement without adequate rehabilitation violates Article 21's right to life with dignity. Tribal communities forced from ancestral lands lose not just shelter but cultural identity, traditional livelihoods, and community structures built over generations. Constitutional protection requires that rehabilitation match the life being lost, not merely the market value of the land."},
      {a:"Art.29",title:"Protection of Cultural and Educational Rights of Minorities",who:"State authorities disregarding tribal cultural distinctiveness",how:"Article 29 protects the right of distinct cultural groups to conserve their language, script, and culture. Tribal communities hold cultural and spiritual relationships with specific lands, forests, and water bodies that cannot be replicated elsewhere. Displacement severs these cultural relationships, effectively extinguishing the 'distinct culture' Article 29 protects — a constitutional harm separate from the land loss itself."},
    ];
    citizenExplanation="Tribal or forest-dwelling communities face displacement. The Constitution specifically protects their land and culture through the Fifth Schedule — this isn't ordinary land, and they aren't ordinary rural communities. Ignoring these protections weakens a constitutional commitment as old as the Republic itself.";
  }
  // COMMUNAL VIOLENCE
  else if(/riot|communal|violence|mob attack/.test(txt)){
    pillar="liberty";delta=-4;
    violations=[
      {a:"Art.21",title:"Right to Life and Personal Liberty",who:"Rioters; state officials failing to prevent or stop violence",how:"Communal violence extinguishes Article 21 rights directly through death and injury. But the constitutional concern extends beyond immediate perpetrators: the Supreme Court in Nandini Sundar (2011) and earlier rulings has held that the state's failure to prevent foreseeable violence itself becomes a constitutional violation. Delayed police response, selective protection, or failure to arrest known instigators transforms non-action into constitutional complicity with violence."},
      {a:"Art.355",title:"Union Duty to Protect States Against Internal Disturbance",who:"Union and State governments",how:"Article 355 imposes a duty on both Union and State governments to protect states against internal disturbance. Communal riots constitute exactly such disturbance. When intelligence warnings are ignored, when paramilitary reinforcement is delayed, or when politically-linked perpetrators escape prosecution, the governments fail their Article 355 duty. This is not optional — it is a direct constitutional command binding both levels of government."},
      {a:"Art.15",title:"Prohibition of Discrimination",who:"Police or administration selectively enforcing law",how:"Communal violence is rarely symmetric — one community typically bears disproportionate harm. When police investigate only one side's violence, when FIRs favour one community, or when compensation and relief flow unequally, Article 15's ban on religious discrimination in state action is violated. The constitutional standard demands equal protection, not merely formal equality, requiring extra state effort where historical or power imbalances exist."},
      {a:"Art.25",title:"Freedom of Religion",who:"Mob targeting religious symbols or worship; state if it failed protection",how:"Article 25 guarantees freedom to profess, practice, and propagate religion. Communal violence typically targets religious identity — places of worship, religious processions, homes and businesses of minority faiths. Even without any specific anti-religious law, mob violence that makes practising one's religion unsafe constitutes a direct violation of Article 25. State failure to protect religious practice is itself a violation of this fundamental right."},
    ];
    citizenExplanation="Communal violence or mob attacks occurred. The state has a constitutional duty to prevent such violence and protect all citizens equally. Beyond the immediate violence, constitutional harm extends to how police, courts, and administration respond — whether all victims get equal protection and justice.";
  }
  // RELIGIOUS FREEDOM — conversion, cow, lynching
  else if(/anti.conversion|religious conversion|cow vigilant|lynching/.test(txt)){
    pillar="religion";delta=-3;inst=inst||"minority";
    violations=[
      {a:"Art.25",title:"Freedom of Religion",who:"State passing anti-conversion law OR mob enforcing social restriction",how:"Article 25 guarantees every person the right to freely profess, practice, AND propagate religion — including the right to change one's religion. The Supreme Court in Rev. Stanislaus (1977) held that Article 25(1) does not protect forcible conversion but clearly protects voluntary conversion. Anti-conversion laws that require government permission for religious change, treat conversion as presumptively suspect, or criminalise facilitation typically overreach constitutional limits and chill voluntary faith choices."},
      {a:"Art.21",title:"Right to Life and Personal Liberty",who:"Mob; police failing to intervene; state officials facilitating impunity",how:"Lynchings and cow-vigilante violence extinguish Article 21 directly. The Supreme Court in Tehseen Poonawalla (2018) mandated specific state actions — nodal officers, fast-track trials, compensation — to address mob lynching as a constitutional failure. Continued lynchings despite these directions constitute contempt of court in addition to underlying rights violations. When victims are disproportionately Muslim or Dalit, Article 14 and 15 violations compound the Article 21 breach."},
      {a:"Art.14",title:"Equality Before Law",who:"Police enforcing law selectively by religious identity",how:"When cattle-transportation laws, conversion allegations, or dietary restrictions get enforced specifically against Muslims, Christians, or Dalits while others commit identical acts without consequence, Article 14's equal protection guarantee is violated. The constitutional command is not whether law exists, but whether it applies equally. Selective enforcement based on community identity constitutes discrimination through facially-neutral rules."},
    ];
    citizenExplanation="Religious freedom is being restricted — through anti-conversion laws, mob violence, or cow-vigilante action. The Constitution guarantees freedom of religion including the right to change religion, and demands equal protection regardless of your faith. These incidents test whether that guarantee is real.";
  }
  // WELFARE
  else if(/welfare|ration|scheme.*cancel|hospital.*shut/.test(txt)){
    pillar="welfare";delta=-2;inst=inst||"health";
    violations=[
      {a:"Art.21",title:"Right to Life and Personal Liberty",who:"Government cancelling or defunding the welfare programme",how:"The Supreme Court has consistently expanded Article 21 beyond mere survival to encompass the right to live with dignity — including access to food, healthcare, shelter, and basic welfare. PUCL v. Union of India (2001) established food security as part of Article 21. Shutting hospitals, cancelling ration schemes, or cutting health budgets directly implicates this expanded reading, even if the programme was not originally created as a constitutional requirement."},
      {a:"Art.47",title:"Duty of State to Raise Level of Nutrition and Public Health",who:"Health ministry or state government",how:"Article 47, a directive principle, obliges the state to raise the level of nutrition and public health as primary duties. While directive principles are not directly enforceable, the Supreme Court in Bandhua Mukti Morcha (1984) held that they inform the content of Article 21 rights. Cutting welfare programmes operates in the opposite constitutional direction — treating what the Constitution calls a 'primary duty' as an optional expense."},
      {a:"Art.39",title:"Principles of Policy — Equal Right to Livelihood",who:"Policy-makers approving the cancellation",how:"Article 39 directs state policy toward ensuring citizens have adequate means of livelihood, equitable distribution of resources, and protection of children and elderly. Welfare cuts typically affect these exact populations disproportionately — the poor, elderly, and children who depend on public services because they cannot access private alternatives. The cut thus violates the constitutional direction not just in substance but in distributive effect."},
    ];
    citizenExplanation="A welfare scheme, hospital, or ration programme is being cut. Citizens have a constitutional right to basic welfare — the Supreme Court has held that Article 21 includes dignified access to health, food, and shelter. Cuts to these services thus engage constitutional rights, not merely policy preferences.";
  }
  // GENERIC FALLBACK
  else{
    dir="negative";delta=-1;
    violations=[
      {a:"Art.21",title:"Right to Life and Personal Liberty",who:"State actor or institution involved",how:"The incident raises potential constitutional concerns that require further evidence and analysis. Article 21 has been interpreted expansively by the Supreme Court to encompass dignity, privacy, shelter, health, education, and a wholesome environment — any of which may be implicated depending on how the story develops. Watch for additional reporting on specific actors, actions, and affected parties to refine the constitutional analysis."},
    ];
    citizenExplanation="A story with potential constitutional implications — watch for further developments. How the case unfolds will determine which specific rights are engaged and whether violations are substantiated.";
  }

  if(delta<=-5)pat="systemic";else if(delta<=-4)pat="repeated";else if(delta<=-3)pat="emerging";else pat="isolated";
  // Confidence based on evidence
  confidence=evidenceLevel==="final_adjudication"?"high":evidenceLevel==="court_finding"?"high":evidenceLevel==="official_doc"?"high":evidenceLevel==="corroborated"?"moderate":evidenceLevel==="allegation"?"low":"moderate";
  let detState=null;for(const st of Object.keys(STATE_BASELINES)){if(txt.includes(st.toLowerCase())){detState=st;break;}}
  const severity=Math.abs(delta)>=5?"critical":Math.abs(delta)>=3?"high":"medium";
  return{pillar,direction:dir,delta,violations,supports,institution:inst,pattern:pat,scope,state:detState,source:"single_source",aiScore:delta,aiDone:false,mythos:null,aiAnalysis:null,severity,evidenceLevel,storyType,confidence,courtStatus,govResponse,citizenExplanation};
}

module.exports = { classify };
