#!/usr/bin/env bash
# Re-extract classify() from src/App.jsx into REGRESSION_classifier.cjs
# for Node-side regression. Run this after any edit to classify().
set -euo pipefail
cd "$(dirname "$0")/.."

# Find classify() line range dynamically so refactors don't break extraction.
RANGE=$(awk '
  /^function classify/ { found=1; depth=0; start=NR }
  found {
    for (i=1; i<=length($0); i++) {
      c = substr($0, i, 1)
      if (c == "{") depth++
      if (c == "}") {
        depth--
        if (depth == 0) { print start","NR; exit }
      }
    }
  }
' src/App.jsx)

START=${RANGE%,*}
END=${RANGE#*,}
echo "Extracting classify() from src/App.jsx lines ${START}-${END}"

# STATE_BASELINES is referenced by classify's scope detection.
BASELINE_LINE=$(grep -n "^const STATE_BASELINES" src/App.jsx | head -1 | cut -d: -f1)

{
  echo "// DTN Mythos v12 — test-only classifier (extracted from App.jsx for Node regression)"
  echo "// Auto-generated by scripts/extract-classifier.sh. Do NOT edit directly —"
  echo "// edit src/App.jsx and re-run the extraction script."
  echo ""
  sed -n "${BASELINE_LINE}p" src/App.jsx
  echo ""
  sed -n "${START},${END}p" src/App.jsx
  echo ""
  echo "module.exports = { classify };"
} > REGRESSION_classifier.cjs

echo "Wrote REGRESSION_classifier.cjs ($(wc -l < REGRESSION_classifier.cjs) lines)"
